version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-gutenberg-explorer-next
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    expose:
      - 5432
